### ISSUE TITLE
bind scroll will lead to another $(window).on('scroll') not working

### ISSUE THREAD

**Issue by nothingrealhappen** [rp4rk/navsync#3]
`$(window).unbind('scroll')`

https://github.com/rp4rk/navsync/blob/master/src/navsync.js#L162

**Comment by rp4rk** [comment]
Good catch, this won't play nice with any parallax scripts.

**Comment by nothingrealhappen** [comment]
setting `unbind` by a option, if `settings.unbind === true` then don't run `unbind`
